### ISSUE TITLE
文档这块实在是太弱了，能不能详细点

### ISSUE THREAD

**Issue by DidoFitch** [aliyun/openapi-core-nodejs-sdk#19]
很多东西都没说是什么，怎么获取，怎么用？？
apiversion又是哪里的version？

**Comment by JacksonTian** [comment]
请问你调用的是哪块业务的 OpenAPI，这个 SDK 是较底层的裸调用支持。面向不同的业务，我们可以生成更详情的 SDK。这个SDK 只要传入 AK 和 Endpoint，其余 API 参数可以通过代码注解即可知道详情。

**Comment by DidoFitch** [comment]
已经解决了，我都试了一下

**Comment by JacksonTian** [comment]
新增了一段关于 AK，endpoint，apiVersion 的介绍。

**Comment by DidoFitch** [comment]
OK，辛苦了
