### ISSUE TITLE
人脸识别的返回码有问题

### ISSUE THREAD

**Issue by Frey-Fu** [aliyun/openapi-core-nodejs-sdk#20]
```
{
    "Data": {
        "StsToken": {
           
        },
        "VerifyToken": {
          
        }
    },
    "RequestId": "",
    "Success": true,
    "Code": "1"
}
```

调用GetVerifyToken这个action返回的json中，code是1，而你们代码core.js里面允许的code却没有1:
   ` this.codes = new Set([200, '200', 'OK', 'Success']);`
这样会导致后面代码里的抛错：
`      if (json.Code && !this.codes.has(json.Code)) {
        var err = new Error(json.Message);
        err.name = json.Code + 'Error';
        err.data = json;
        err.code = json.Code;
        err.url = url;
        err.entry = entry;
        return Promise.reject(err);
      }`
请让对应的开发人员修改一下返回值好吗，这个错误太低级了。

**Comment by Frey-Fu** [comment]
我猜，可能阿里这边做人脸识别api服务器的老哥们根本不知道有这个sdk 😂

**Comment by Frey-Fu** [comment]
更不用说联调一下了

**Comment by JacksonTian** [comment]
请问，具体是哪个云产品？

**Comment by Frey-Fu** [comment]
实人认证

**Comment by JacksonTian** [comment]
endpoint 发一下吧。

**Comment by Frey-Fu** [comment]
https://cloudauth.aliyuncs.com

**Comment by JacksonTian** [comment]
已经反馈给业务方了。你可以临时性的通过

```js
client.codes = client.codes.add('1');
```

来避开这个问题。
