### ISSUE TITLE
请增加promise返回支持，并建议加入typescript支持。

### ISSUE THREAD

**Issue by xihuanhh** [aliyun/openapi-core-nodejs-sdk#3]
我测试过发现该库不支持 bluebird库的promisfyAll 函数将推送的API都转换成promise返回，
烦请看一下是否可以增加promise的支持。
如果有可能也烦请是否可以加入typescript支持。

**Comment by JacksonTian** [comment]
request 方法本身就是返回promise的。无需再转换。

**Comment by xihuanhh** [comment]
@JacksonTian  噢 突然发现这不是官网那个依赖包的版本 就是 npm上的 aliyun-sdk 里的 PUSH

**Comment by JacksonTian** [comment]
参见 README.
