### ISSUE TITLE
Support for security token?

### ISSUE THREAD

**Issue by arafato** [aliyun/openapi-core-nodejs-sdk#30]
Hi--, 

does this SDK also support security token? 
If this SDK is used on an ECS instance for example that has an assigned role, I want to use the sts token along with the access key id and access key secret. Is this supported? Thanks!

**Comment by JacksonTian** [comment]
Not supported. We will provide it asap.

**Comment by arafato** [comment]
Cool, thanks! Any approximate timeline?

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by imbolo** [comment]
@arafato You can simply define a OpenAPIClient extends from the class 'pop-core', like this:
```js
const BaseOpenAPIClient = require('@alicloud/pop-core');

module.exports = class OpenAPIClient extends BaseOpenAPIClient {
  constructor(config, verbose) {
    super(config, verbose);
    if (config.securityToken) {
      this.securityToken = config.securityToken;
    }
  }

  _buildParams() {
    let params = super._buildParams();
    if (this.securityToken) {
      params['SecurityToken'] = this.securityToken;
    }
    return params;
  }
}
```

And then, using the new OpenAPIClient where you need to make a OpenAPI request.

```
const OpenAPIClient = require('./OpenAPIClient');
const openAPIClient = new OpenAPIClient({
  endpoint: 'xxx',
  apiVersion: 'xxx',
  accessKeyId: 'xxx',
  accessKeySecret: 'xxx',
  securityToken: 'xxx'
});
```

**Comment by JacksonTian** [comment]
It's supported now. Just pass `securityToken` in config, no need to extends it.

**Comment by JacksonTian** [comment]
Thanks @imbolo
