### ISSUE TITLE
core.d.ts 有问题

### ISSUE THREAD

**Issue by shepherdwind** [aliyun/openapi-core-nodejs-sdk#37]
![image](https://user-images.githubusercontent.com/452899/45281048-3434aa80-b509-11e8-9c27-8f5c74c87c22.png)

只有 core 有类型描述，ROAClient 没有，没法用。建议先去掉 core.d.ts ，或者补全接口描述。

**Comment by JacksonTian** [comment]
欢迎 PR 一下。

**Comment by shynome** [comment]
RPCClient 的定义也缺少

**Comment by JacksonTian** [comment]
PR、PR
