### ISSUE TITLE
ERROR in ./server.js from UglifyJs

### ISSUE THREAD

**Issue by StevenCao99** [aliyun/openapi-core-nodejs-sdk#44]
ERROR in ./server.js from UglifyJs
Unexpected character '`' [./~/@alicloud/pop-core/lib/core.js:33,0][./server.js:1384,9]

ERROR in ./server.js from UglifyJs
Unexpected character '`' [./server.js:1,14952]

node v9.11.1
npm v6.4.1

**Comment by JacksonTian** [comment]
Server.js 不是您自己的文件吗？

**Comment by StevenCao99** [comment]
已经解决，谢谢。
