### ISSUE TITLE
RPCClient 如何设置HTTP的Body参数

### ISSUE THREAD

**Issue by dingwb1015** [aliyun/openapi-core-nodejs-sdk#47]
在@alicloud/pop-core的RPCClient的request中，如何将参数设置到HTTP POST请求的Body中：

`client.request(action, params, options);`

**Comment by dingwb1015** [comment]
欢迎 PR.

**Comment by PandaTsui** [comment]
貌似只能url传参？ 请问你有序列化的代码吗，借用一下。

**Comment by JacksonTian** [comment]
请提供一下具体的 API。我可以提供示例代码。

**Comment by JacksonTian** [comment]
RPC 通常都是 QueryString 传参数。
