### ISSUE TITLE
List<String, Object> 类型数据格式化有问题。

### ISSUE THREAD

**Issue by JackieLs** [aliyun/openapi-core-nodejs-sdk#48]
```js
  const params = {
    DomainRecordInfo: [
      {
        Domain: "1.com"
      }
    ],
    Type: 'DOMAIN_ADD'
  };
// expect: DomainRecordInfo.1.Domain=1.com
// but got: DomainRecordInfo.1=%5Bobject%20Object%5D
```
下面这行代码直接就赋值了，normalize 的方式不正确。我可以提个pr。

https://github.com/aliyun/openapi-core-nodejs-sdk/blob/bee7137ca336476562442cc4064597b727d5c059/lib/core.js#L50

**Comment by JacksonTian** [comment]
PR 呢。

**Comment by JacksonTian** [comment]
const params = {
    DomainRecordInfo.1.Domain:  "1.com"
    Type: 'DOMAIN_ADD'
  };

**Comment by JacksonTian** [comment]
New version was released for fix this issue.
