### ISSUE TITLE
Can I use the sdk behind proxy?

### ISSUE THREAD

**Issue by naughtbeing** [aliyun/openapi-core-nodejs-sdk#54]
I've tried like this
process.env.http_proxy='http://xxxx';
but it wont work

Are there any other ways?

**Comment by JacksonTian** [comment]
Not ready now.

**Comment by JacksonTian** [comment]
```js
var tunnel = require('tunnel-agent');

client.request(action, params, {
  agent: tunnel.httpOverHttp({
    proxy: {
      host: 'host',
      port: port
    }
  });
});
```

麻烦您结合 tunnel-agent 模块一起试一下。

**Comment by JacksonTian** [comment]
Hi @naughtbeing Did you question fixed? I will close this issue, if any questions, feel free to re-open it.

**Comment by gohiei** [comment]
I use the [http-proxy-agent](https://www.npmjs.com/package/http-proxy-agent) for proxy (replace the tuneel-agent), and it works well.
