### ISSUE TITLE
影响使用：通过 client 发送获取实人认证的 token ，code 1 引发 SDK 内部判断错误

### ISSUE THREAD

**Issue by OhIAmFine** [aliyun/openapi-core-nodejs-sdk#64]
在使用 client 访问获取实人认证的 token 时，接口参数都仔细校验无误，但是请求在响应的时候抛出了 ERROR：

![image](https://user-images.githubusercontent.com/10390004/61369863-a2819080-a8c3-11e9-8aa7-c8b00abe05aa.png)

通过 stack 查看 SDK 发现，返回的 code 为 ‘1’，不在判断的逻辑中，所以抛出了错误
![image](https://user-images.githubusercontent.com/10390004/61370070-1d4aab80-a8c4-11e9-90a5-16447c8cb938.png)

但是返回的数据确实是我所需要的，我不能每次去抛出的 Error中去获取我需要的数据吧。

**Comment by JacksonTian** [comment]
在 new Client 的时候 传入 codes ，把这个 "1" 加入进去。

https://github.com/aliyun/openapi-core-nodejs-sdk/blob/master/lib/rpc.js#L124

**Comment by OhIAmFine** [comment]
@JacksonTian 为什么文档上面不写呢，这样每个人都会遇到这个问题，如果他们不去看issue，恐怕就要放弃这个产品的使用了

**Comment by songshenzong** [comment]
> @JacksonTian 为什么文档上面不写呢，这样每个人都会遇到这个问题，如果他们不去看issue，恐怕就要放弃这个产品的使用了

如果存在，我们会尽快补充，请保持对阿里云产品的信心。

**Comment by OhIAmFine** [comment]
@songshenzong 报告宋神宗陛下，这个问题确实存在，不仅是在本地 `nodejs` 程序，还是在 `API Explorer` 中调试，都会出错，就是因为返回的 codes 存在的原因，我看这边好几个 issue 都是这类问题，请尽快修复吧，或者在文档中附加说明一下。

**Comment by songshenzong** [comment]
> @songshenzong 报告宋神宗陛下，这个问题确实存在，不仅是在本地 `nodejs` 程序，还是在 `API Explorer` 中调试，都会出错，就是因为返回的 codes 不合理的原因，我看这边好几个 issue 都是这类问题，请尽快修复吧，或者在文档中附加说明一下。

好的，你先退下，搞好了派人联系你。

**Comment by songshenzong** [comment]
> @songshenzong 报告宋神宗陛下，这个问题确实存在，不仅是在本地 `nodejs` 程序，还是在 `API Explorer` 中调试，都会出错，就是因为返回的 codes 不合理的原因，我看这边好几个 issue 都是这类问题，请尽快修复吧，或者在文档中附加说明一下。

hello，下次遇到这种问题可以提工单哦。
