### ISSUE TITLE
RPCClient 支持  post 方式传入 body 吗

### ISSUE THREAD

**Issue by OhIAmFine** [aliyun/openapi-core-nodejs-sdk#65]
在进行实人认证的时候，首先需要获取 token ，而获取 token 中有一步是需要将 Binding 传入到 body 中，我在 SDK 中传入 body 方式但是返回的 token 是无效的，请问 SDK 中如何将 body 放入到 post 请求中呢
![image](https://user-images.githubusercontent.com/10390004/61772897-eaee0080-ae25-11e9-8bf6-fc21a1d6b90b.png)
![image](https://user-images.githubusercontent.com/10390004/61772920-f8a38600-ae25-11e9-840a-f3e14921b25a.png)

**Comment by songshenzong** [comment]
请按照参数说明传入。

**Comment by JacksonTian** [comment]
@OhIAmFine 请问是否还有问题。这个 issue 我们暂时先关闭。如果仍然有问题，请 re-open 。
