### ISSUE TITLE
node 高版本 12.13.1 会有 DeprecationWarning

### ISSUE THREAD

**Issue by coco-super** [aliyun/openapi-core-nodejs-sdk#69]
fun 调用时候会有 DeprecationWarning，建议将废弃的 api 修掉。
warning：
`(node:11670) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`

相关链接：
https://octolinker-demo.now.sh/heroku/node-heroku-client/pull/94
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames

**Comment by JacksonTian** [comment]
fixed.

**Comment by vangie** [comment]
@JacksonTian fix 的版本已经修复了么？
