### ISSUE TITLE
调用 sts 时报错 Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by DuanPengfei** [aliyun/openapi-core-nodejs-sdk#72]
Client network socket disconnected before secure TLS connection was established GET https://sts-vpc.cn-zhangjiakou.aliyuncs.com

这个问题如何定位呢？联系了 sts 的同学，他们提供的信息是 tls 支持 1.0、1.1、1.2，Node.js 版本是10.18。

**Comment by JacksonTian** [comment]
可能跟证书有关。
