### ISSUE TITLE
electron内运行报错

### ISSUE THREAD

**Issue by StarkShang** [aliyun/openapi-core-nodejs-sdk#78]
在electron里调用短信接口，报错

> Access to fetch at 'https://dysmsapi.aliyuncs.com/' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field x-sdk-client is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by JacksonTian** [comment]
目前阿里云的 OpenAPI 因为安全的原因，不适合从端侧进行直接调用。请从服务端发起调用。
