### ISSUE TITLE
CDN新版SDK文档应该把这个给NodeJS使用的加进去

### ISSUE THREAD

**Issue by oscxc** [aliyun/openapi-core-nodejs-sdk#87]
TypeScript 本身就兼容 JavaScript，不需要再提供 TypeScript 版本。
TypeScript 与 JavaScript 只是编程语言，NodeJS才叫服务器端，由于NodeJS用JavaScript写，所以这两个都可以。
TypeScript 也不应该与Python、PHP、Java、C++、C#这些后端语言相提并论，NodeJS才行。

**Comment by JacksonTian** [comment]
推荐新的文档：https://next.api.aliyun.com/api-tools/sdk/Cdn?version=2018-05-10&language=nodejs-tea
